### ISSUE TITLE
Can't resize GTK apps

### ISSUE THREAD

**Issue by pharaone** [AlanGriffiths/egmde#7]
When trying resizing apps Qt ones can be resized, but GTK apps can't.

**Comment by AlanGriffiths** [comment]
Yes, this is because GTK places the resize border outside the window, and Mir's default event handling restricts the active input region to the window. (So the client doesn't see the cursor in this region.)

Mir can handle this, it just needs some code writing to implement the non-default input region. (This is another thing that ought to be swept up in the next Mir release or two.)

**Comment by AlanGriffiths** [comment]
This is now fixed in Mir development. You can try it out with ppa:mir-team/dev:
```
$ sudo apt-add-repository ppa:mir-team/dev
$ sudo apt update
$ sudo apt upgrade
```

**Comment by pharaone** [comment]
I'll try it, thanks!

Il ven 27 apr 2018, 16:15 Alan Griffiths <notifications@github.com> ha
scritto:

**Comment by pharaone** [comment]
Now everything is working, thanks!
